/**
 * Supabase Database Types
 *
 * This file will be generated/updated by Supabase CLI in the future.
 * For now, we define a minimal placeholder structure.
 */

// Placeholder Database type - will be generated by Supabase CLI
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      readings: {
        Row: {
          id: string;
          user_id: string;
          reading_type: string;
          input_data: Record<string, unknown>;
          result_data: Record<string, unknown>;
          title: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          reading_type: string;
          input_data: Record<string, unknown>;
          result_data: Record<string, unknown>;
          title?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          reading_type?: string;
          input_data?: Record<string, unknown>;
          result_data?: Record<string, unknown>;
          title?: string | null;
          created_at?: string;
        };
      };
      credits: {
        Row: {
          id: string;
          user_id: string;
          credits: number;
          last_check_in: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          credits?: number;
          last_check_in?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          credits?: number;
          last_check_in?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}

// Credits state type
export interface CreditsState {
  credits: number;
  checkedInToday: boolean;
}

// Function return types for RPC calls
export interface GetCreditsResult {
  credits: number;
  checked_in_today: boolean;
  bonus_awarded: boolean;
}

export interface DeductCreditResult {
  success: boolean;
  remaining_total: number;
  /** @deprecated Session 58 unified credit pools - daily_credits merged into total_credits. This field is always 0. */
  remaining_daily: number;
  error_message: string | null;
  referral_bonus_claimed: boolean;
  referral_bonus_amount: number;
}
