/**
 * Supabase Database Types
 *
 * This file will be generated/updated by Supabase CLI in the future.
 * For now, we define a minimal placeholder structure.
 */

// Placeholder Database type - will be generated by Supabase CLI
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      readings: {
        Row: {
          id: string;
          user_id: string;
          reading_type: string;
          input_data: Record<string, unknown>;
          result_data: Record<string, unknown>;
          title: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          reading_type: string;
          input_data: Record<string, unknown>;
          result_data: Record<string, unknown>;
          title?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          reading_type?: string;
          input_data?: Record<string, unknown>;
          result_data?: Record<string, unknown>;
          title?: string | null;
          created_at?: string;
        };
      };
      credits: {
        Row: {
          id: string;
          user_id: string;
          credits: number;
          last_check_in: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          credits?: number;
          last_check_in?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          credits?: number;
          last_check_in?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}

// Credits state type
export interface CreditsState {
  credits: number;
  checkedInToday: boolean;
}
