/**
 * Major Arcana - Cards 12-21
 * The Hanged Man through The World
 */

import type { TarotCard } from './types';

export const majorArcanaContinued: TarotCard[] = [
  {
    number: 12,
    name: { en: 'The Hanged Man', zh: '倒吊人', ja: '吊るされた男' },
    arcana: 'major',
    keywords: ['surrender', 'letting go', 'new perspective', 'pause', 'sacrifice', 'suspension', 'waiting', 'contemplation'],
    upright: 'Voluntary sacrifice for higher purpose. Let go of control, see from different angle.',
    reversed: 'Resistance to sacrifice, stalling, delaying inevitable decision.',
    astrology: { ruling: 'Neptune', element: 'water' },
    numerology: { number: 12, meaning: 'Completion, cosmic order, pause before transformation' },
    symbols: ['Man suspended upside-down', 'Living tree', 'Serene expression', 'Crossed leg', 'Halo', 'Red pants', 'Blue tunic'],
    love: { upright: 'Feeling trapped, not time for commitments', reversed: 'Unwillingness to make sacrifices' },
    career: { upright: 'Period of uncertainty, wait for more information', reversed: 'Stalling on decisions' },
    health: 'Red flag about procrastinated health issues',
    yesNo: 'Maybe',
    advice: 'Surrender control. See your situation from a different perspective.'
  },
  {
    number: 13,
    name: { en: 'Death', zh: '死神', ja: '死神' },
    arcana: 'major',
    keywords: ['transformation', 'endings', 'change', 'transition', 'rebirth', 'letting go', 'release', 'new beginnings'],
    upright: 'Profound transformation—end of one phase, beginning of another. Release the old.',
    reversed: 'Resistance to necessary change, fear of transformation, being stuck.',
    astrology: { ruling: 'Scorpio', element: 'water' },
    numerology: { number: 13, meaning: 'Transformation, death/rebirth cycles' },
    symbols: ['Skeleton in armor', 'White horse', 'Black banner with white rose', 'Fallen figures', 'Rising sun', 'River'],
    love: { upright: 'Major transformation, ending or deeper phase', reversed: 'Clinging to failing relationship' },
    career: { upright: 'Career transformation, leaving outdated approach', reversed: 'Refusing to adapt' },
    health: 'End of health challenges, major lifestyle changes needed',
    yesNo: 'No',
    advice: 'Embrace endings as necessary for new beginnings.'
  },
  {
    number: 14,
    name: { en: 'Temperance', zh: '节制', ja: '節制' },
    arcana: 'major',
    keywords: ['balance', 'moderation', 'patience', 'harmony', 'purpose', 'alchemy', 'healing', 'integration', 'middle path'],
    upright: 'Balance, peace, patience. Blending diverse elements to create something valuable.',
    reversed: 'Imbalance, excess, extremes, overindulgence.',
    astrology: { ruling: 'Sagittarius', element: 'fire' },
    numerology: { number: 14, meaning: 'Balance, harmony, adaptability' },
    symbols: ['Winged angel', 'Light blue robe', 'One foot on rocks/water', 'Two cups with flowing water', 'Irises', 'Winding path'],
    love: { upright: 'Harmonious partnership, soulmates', reversed: 'Imbalance, disharmony' },
    career: { upright: 'Set goals with patience, hard work noticed', reversed: 'Lack of work-life balance' },
    health: 'Moderation key to good health',
    yesNo: 'Yes',
    advice: 'Practice moderation. Blend opposing forces to create harmony.'
  },
  {
    number: 15,
    name: { en: 'The Devil', zh: '恶魔', ja: '悪魔' },
    arcana: 'major',
    keywords: ['shadow self', 'attachment', 'addiction', 'restriction', 'bondage', 'materialism', 'sexuality', 'temptation'],
    upright: 'Shadow side and negative forces. Trapped by unhealthy attachments. The chains are loose.',
    reversed: 'Breaking free from attachments, overcoming addiction, spiritual liberation.',
    astrology: { ruling: 'Capricorn', element: 'earth' },
    numerology: { number: 15, meaning: 'Reduces to 6 (Lovers connection), duality of choice' },
    symbols: ['Baphomet', 'Inverted pentagram', 'Chained figures', 'Bat wings', 'Horns on humans', 'Tails', 'Torch'],
    love: { upright: 'Intense passion but watch for codependency', reversed: 'Breaking free from unhealthy relationship' },
    career: { upright: 'Feeling trapped in unfulfilling job', reversed: 'Breaking free from dead-end career' },
    health: 'Issues related to addiction, negative patterns',
    yesNo: 'No',
    advice: 'Acknowledge the chains that bind you—only then can you remove them.'
  },
  {
    number: 16,
    name: { en: 'The Tower', zh: '塔', ja: '塔' },
    arcana: 'major',
    keywords: ['sudden change', 'upheaval', 'chaos', 'revelation', 'awakening', 'destruction', 'liberation', 'breakthrough'],
    upright: 'Sudden upheaval shaking foundations. Destruction is necessary for authentic rebuilding.',
    reversed: 'Resisting inevitable change, delaying the inevitable, averting disaster.',
    astrology: { ruling: 'Mars', element: 'fire' },
    numerology: { number: 16, meaning: 'Reduces to 7—spiritual awakening through crisis' },
    symbols: ['Tower on mountain', 'Lightning bolt', 'Falling crown', 'Falling figures', 'Flames', 'Grey clouds', 'Yod flames'],
    love: { upright: 'Sudden relationship upheaval, shocking revelation', reversed: 'Avoiding necessary breakup' },
    career: { upright: 'Job loss, business failure, crisis', reversed: 'Narrowly avoiding job loss' },
    health: 'Sudden health crisis, body demanding attention',
    yesNo: 'No',
    advice: 'Let lightning strike away your illusions. From destruction comes liberation.'
  },
  {
    number: 17,
    name: { en: 'The Star', zh: '星星', ja: '星' },
    arcana: 'major',
    keywords: ['hope', 'faith', 'renewal', 'inspiration', 'serenity', 'healing', 'spirituality', 'purpose', 'calm'],
    upright: 'Hope and renewed faith after devastation. Spiritual connection and inner peace.',
    reversed: 'Lost faith, despair, disconnection from spiritual self.',
    astrology: { ruling: 'Aquarius', element: 'air' },
    numerology: { number: 17, meaning: 'Reduces to 8—infinite potential' },
    symbols: ['Naked woman', 'One foot on land/water', 'Two pitchers', 'Large star', 'Seven smaller stars', 'Pool', 'Lush landscape'],
    love: { upright: 'Renewed hope in love, healing from heartbreak', reversed: 'Feeling hopeless about love' },
    career: { upright: 'Positive opportunities, recognition', reversed: 'Lack of motivation' },
    health: 'Excellent healing energy, recovery',
    yesNo: 'Yes',
    advice: 'After darkness comes starlight. Let your authentic light shine.'
  },
  {
    number: 18,
    name: { en: 'The Moon', zh: '月亮', ja: '月' },
    arcana: 'major',
    keywords: ['illusion', 'fear', 'anxiety', 'subconscious', 'intuition', 'uncertainty', 'deception', 'dreams', 'hidden truths'],
    upright: 'Realm of illusion and subconscious. Things are not what they seem. Trust instincts.',
    reversed: 'Emerging from confusion, fears subsiding, truth revealed.',
    astrology: { ruling: 'Pisces', element: 'water' },
    numerology: { number: 18, meaning: 'Reduces to 9—completion, spiritual wisdom' },
    symbols: ['Full moon with face', 'Crescent moon', 'Two towers', 'Dog and wolf', 'Crayfish', 'Pool', 'Winding path'],
    love: { upright: 'Uncertainty, hidden truths, fears distorting perception', reversed: 'Secrets revealed, clarity' },
    career: { upright: 'Confusion, workplace deception, avoid major decisions', reversed: 'Clarity emerging' },
    health: 'Mental health focus—anxiety, sleep disturbances',
    yesNo: 'Maybe',
    advice: 'Not everything is as it appears. Trust intuition over logic.'
  },
  {
    number: 19,
    name: { en: 'The Sun', zh: '太阳', ja: '太陽' },
    arcana: 'major',
    keywords: ['joy', 'success', 'positivity', 'vitality', 'warmth', 'abundance', 'happiness', 'celebration', 'enlightenment', 'truth'],
    upright: 'Most positive card—pure joy, success, vitality. Your energy is magnetic.',
    reversed: 'Still positive but dimmed. Struggling to see the bright side.',
    astrology: { ruling: 'Sun', element: 'fire' },
    numerology: { number: 19, meaning: 'Reduces to 1—new beginnings, unity, success' },
    symbols: ['Radiant sun', 'Naked child', 'White horse', 'Red banner', 'Four sunflowers', 'Stone wall'],
    love: { upright: 'Joyful relationships, engagement/marriage/family', reversed: 'Taking relationship for granted' },
    career: { upright: 'Career success, recognition, achievement', reversed: 'Temporary setbacks' },
    health: 'Excellent vitality, robust physical health',
    yesNo: 'Strong Yes',
    advice: 'Let your light shine brightly. Celebrate your accomplishments.'
  },
  {
    number: 20,
    name: { en: 'Judgement', zh: '审判', ja: '審判' },
    arcana: 'major',
    keywords: ['rebirth', 'inner calling', 'absolution', 'self-evaluation', 'awakening', 'renewal', 'transformation', 'second chances'],
    upright: 'Spiritual awakening and call to higher purpose. All pieces coming together.',
    reversed: 'Ignoring inner calling, refusing to learn from past, excessive self-doubt.',
    astrology: { ruling: 'Pluto', element: 'fire' },
    numerology: { number: 20, meaning: 'Reduces to 2—duality, partnership, choices' },
    symbols: ['Archangel Gabriel', 'Trumpet', 'White flag with cross', 'Rising figures', 'Open arms', 'Mountains', 'Blue water'],
    love: { upright: 'Honest evaluation, second chances, forgiveness', reversed: 'Judging partner too harshly' },
    career: { upright: 'Being evaluated, career awakening, discovering calling', reversed: 'Avoiding needed changes' },
    health: 'Period of healing and wholeness',
    yesNo: 'Yes',
    advice: 'Answer the call of your highest self. Rise to meet your purpose.'
  },
  {
    number: 21,
    name: { en: 'The World', zh: '世界', ja: '世界' },
    arcana: 'major',
    keywords: ['completion', 'achievement', 'fulfillment', 'wholeness', 'integration', 'accomplishment', 'travel', 'success', 'closure'],
    upright: 'Successful completion of major life cycle. State of wholeness. This ending is a new beginning.',
    reversed: 'Incomplete cycles, unfinished business, lack of closure.',
    astrology: { ruling: 'Saturn', element: 'earth' },
    numerology: { number: 21, meaning: 'Reduces to 3—creative expression, completion' },
    symbols: ['Dancing figure', 'Two wands', 'Purple sash', 'Laurel wreath', 'Red ribbons', 'Four corner figures'],
    love: { upright: 'Relationship reaching fulfillment—engagement, marriage', reversed: 'Seeking closure from past' },
    career: { upright: 'Major achievement, professional pinnacle', reversed: 'Projects incomplete' },
    health: 'Complete recovery, achieving wellness goals',
    yesNo: 'Strong Yes',
    advice: 'You have arrived. Honor how far you\'ve come. Prepare for the next adventure.'
  }
];
