/**
 * Major Arcana - Complete 22 Cards
 * The Fool (0) through The World (21)
 */

import type { TarotCard } from './types';

export const majorArcana: TarotCard[] = [
  {
    number: 0,
    name: { en: 'The Fool', zh: '愚者', ja: '愚者' },
    arcana: 'major',
    keywords: ['beginnings', 'innocence', 'spontaneity', 'free spirit', 'adventure', 'potential', 'leap of faith', 'optimism', 'trust'],
    upright: 'New beginnings, unlimited potential, leap of faith into the unknown. Embrace adventure with childlike wonder.',
    reversed: 'Fear of unknown, recklessness, taking too many risks without considering consequences.',
    astrology: { ruling: 'Uranus', element: 'air' },
    numerology: { number: 0, meaning: 'Unlimited potential, infinite possibilities' },
    symbols: ['Young man at cliff', 'White rose', 'Knapsack', 'White dog', 'Mountains', 'Yellow sky'],
    love: { upright: 'Exciting spontaneous romance, carefree love', reversed: 'Risky behavior causing insecurity' },
    career: { upright: 'New job opportunity, fresh professional start', reversed: 'Hesitation about new ventures' },
    health: 'Fresh starts in health routines, spontaneity in wellness',
    yesNo: 'Yes',
    advice: 'Take the leap of faith. Trust the Universe to guide you.'
  },
  {
    number: 1,
    name: { en: 'The Magician', zh: '魔术师', ja: '魔術師' },
    arcana: 'major',
    keywords: ['manifestation', 'resourcefulness', 'power', 'inspired action', 'willpower', 'creation', 'skill', 'concentration'],
    upright: 'You have all tools needed to manifest dreams. Take inspired, focused action.',
    reversed: 'Exploring ideas without action, manipulation, misdirected efforts.',
    astrology: { ruling: 'Mercury', element: 'air' },
    numerology: { number: 1, meaning: 'New beginnings, individuality, leadership' },
    symbols: ['One hand up, one down', 'Infinity symbol', 'Four suit symbols', 'Ouroboros belt', 'Garden'],
    love: { upright: 'Taking active role in love, power to attract', reversed: 'Disconnected from magnetism, dishonest partner' },
    career: { upright: 'Resources for abundance, everything needed to succeed', reversed: 'Lacking clarity on goals' },
    health: 'Transformation possible through awareness',
    yesNo: 'Yes',
    advice: 'Channel your energy and manifest your vision through action.'
  },
  {
    number: 2,
    name: { en: 'The High Priestess', zh: '女祭司', ja: '女教皇' },
    arcana: 'major',
    keywords: ['intuition', 'unconscious', 'inner voice', 'mystery', 'spirituality', 'higher power', 'wisdom', 'secrets', 'divine feminine'],
    upright: 'Listen to intuition over intellect. Answers are within, not without.',
    reversed: 'Difficulty listening to intuition, confusion, ignoring gut feelings.',
    astrology: { ruling: 'Moon', element: 'water' },
    numerology: { number: 2, meaning: 'Duality, balance, receptivity, intuition' },
    symbols: ['Two pillars', 'Crown of Isis', 'Crescent moon', 'Pomegranates', 'Torah scroll', 'Blue robes'],
    love: { upright: 'Increasing intimacy, patience needed', reversed: 'Ignoring intuition, hiding true self' },
    career: { upright: 'Period of education, rely on gut instincts', reversed: 'Beware hidden agendas' },
    health: 'Trust body\'s signals, meditation needed',
    yesNo: 'Maybe',
    advice: 'Go within. Trust your intuition.'
  },
  {
    number: 3,
    name: { en: 'The Empress', zh: '皇后', ja: '女帝' },
    arcana: 'major',
    keywords: ['femininity', 'beauty', 'nature', 'nurturing', 'abundance', 'fertility', 'motherhood', 'creativity', 'sensuality'],
    upright: 'Deep connection with feminine energy. Period of growth where dreams come to fruition.',
    reversed: 'Need for self-care, creative blocks, giving away personal power.',
    astrology: { ruling: 'Venus', element: 'earth' },
    numerology: { number: 3, meaning: 'Creativity, expression, growth, abundance' },
    symbols: ['Crown of 12 stars', 'Venus shield', 'Scepter', 'Pomegranate robe', 'Flowing stream', 'Wheat field'],
    love: { upright: 'Nurturing partner, deep emotional bonds, possible pregnancy', reversed: 'Over-dependence, smothering' },
    career: { upright: 'Creative projects flourishing, abundance', reversed: 'Creative blocks, burnout' },
    health: 'Fertility indicator, connect with nature for healing',
    yesNo: 'Yes',
    advice: 'Nurture yourself and your creations. Connect with nature.'
  },
  {
    number: 4,
    name: { en: 'The Emperor', zh: '皇帝', ja: '皇帝' },
    arcana: 'major',
    keywords: ['authority', 'structure', 'control', 'fatherhood', 'stability', 'leadership', 'discipline', 'power', 'protection'],
    upright: 'Structure, stability, leadership. Create order from chaos through rational thinking.',
    reversed: 'Excessive control, rigidity, tyranny, lack of discipline.',
    astrology: { ruling: 'Aries', element: 'fire' },
    numerology: { number: 4, meaning: 'Stability, foundation, structure, order' },
    symbols: ['Stone throne with rams', 'Armor', 'Ankh scepter', 'Orb', 'White beard', 'Barren mountains'],
    love: { upright: 'Stable partnership, protective partner', reversed: 'Controlling partner, power struggles' },
    career: { upright: 'Strong leadership, business success', reversed: 'Conflicts with authority' },
    health: 'Discipline in health routines needed',
    yesNo: 'Yes',
    advice: 'Take command with strength and wisdom. Build solid foundations.'
  },
  {
    number: 5,
    name: { en: 'The Hierophant', zh: '教皇', ja: '法王' },
    arcana: 'major',
    keywords: ['tradition', 'conformity', 'morality', 'ethics', 'spiritual wisdom', 'religion', 'institutions', 'education', 'guidance'],
    upright: 'Follow established processes. Seek wisdom from institutions and mentors.',
    reversed: 'Rebellion, challenging traditions, exploring own spiritual path.',
    astrology: { ruling: 'Taurus', element: 'earth' },
    numerology: { number: 5, meaning: 'Change, freedom, exploration' },
    symbols: ['Triple crown', 'Papal staff', 'Two acolytes', 'Raised hand', 'Two pillars', 'Crossed keys'],
    love: { upright: 'Traditional relationship, marriage indicator', reversed: 'Unconventional relationship' },
    career: { upright: 'Working with established institutions, seeking mentor', reversed: 'Breaking from corporate culture' },
    health: 'Seek guidance from professionals',
    yesNo: 'Yes',
    advice: 'Honor tradition while remaining open to what no longer serves you.'
  },
  {
    number: 6,
    name: { en: 'The Lovers', zh: '恋人', ja: '恋人' },
    arcana: 'major',
    keywords: ['love', 'harmony', 'relationships', 'values alignment', 'choices', 'union', 'partnership', 'attraction', 'soulmates'],
    upright: 'Meaningful relationships built on trust. Decision-making at crossroads. Soulmate connection.',
    reversed: 'Conflict, disharmony, torn between head and heart, possible infidelity.',
    astrology: { ruling: 'Gemini', element: 'air' },
    numerology: { number: 6, meaning: 'Harmony, balance, love, responsibility, choice' },
    symbols: ['Archangel Raphael', 'Adam and Eve', 'Tree of Knowledge', 'Tree of Life', 'Mountain', 'Sun'],
    love: { upright: 'Deep connection, soulmate energy, harmonious partnership', reversed: 'Communication breakdown, betrayal' },
    career: { upright: 'Important decisions, successful partnerships', reversed: 'Workplace conflict' },
    health: 'Balance between mind and body important',
    yesNo: 'Yes',
    advice: 'Make choices from your heart that align with your deepest values.'
  },
  {
    number: 7,
    name: { en: 'The Chariot', zh: '战车', ja: '戦車' },
    arcana: 'major',
    keywords: ['willpower', 'determination', 'success', 'control', 'direction', 'victory', 'ambition', 'focus', 'overcoming obstacles'],
    upright: 'Overcoming challenges through control and willpower. Victory awaits the determined.',
    reversed: 'Feeling powerless, lacking direction. Regain drive and determination.',
    astrology: { ruling: 'Cancer', element: 'water' },
    numerology: { number: 7, meaning: 'Spirituality, introspection, victory through inner strength' },
    symbols: ['Charioteer standing', 'Black and white sphinxes', 'Crescent moon armor', 'Laurel crown', 'Star canopy', 'Wand'],
    love: { upright: 'Working through challenges together', reversed: 'Relationship off course, power struggles' },
    career: { upright: 'Ambition taking you far, competitive success', reversed: 'Career feeling directionless' },
    health: 'Victory over health challenges through determination',
    yesNo: 'Yes',
    advice: 'Take control of your destiny. Drive forward with determination.'
  },
  {
    number: 8,
    name: { en: 'Strength', zh: '力量', ja: '力' },
    arcana: 'major',
    keywords: ['inner strength', 'courage', 'compassion', 'patience', 'influence', 'self-control', 'determination', 'resilience'],
    upright: 'Inner power and calm mastery over instincts. Approach with compassion, not force.',
    reversed: 'Depleted self-confidence, vulnerability, explosive behavior.',
    astrology: { ruling: 'Leo', element: 'fire' },
    numerology: { number: 8, meaning: 'Power, karma, material success, cycles' },
    symbols: ['Woman taming lion', 'White robe', 'Infinity symbol', 'Flower crown and belt', 'Blue background'],
    love: { upright: 'Passionate romance, compassion attracting partners', reversed: 'Codependency, insecurity' },
    career: { upright: 'Bold career moves possible', reversed: 'Impostor syndrome' },
    health: 'Good stamina, balance energy with rest',
    yesNo: 'Yes',
    advice: 'Trust your inner strength. Overcome through patience and compassion.'
  },
  {
    number: 9,
    name: { en: 'The Hermit', zh: '隐士', ja: '隠者' },
    arcana: 'major',
    keywords: ['soul-searching', 'introspection', 'solitude', 'inner guidance', 'wisdom', 'contemplation', 'meditation'],
    upright: 'Taking a break to draw energy inward. Answers are deep within your soul.',
    reversed: 'Not taking enough time for reflection OR too much isolation.',
    astrology: { ruling: 'Virgo', element: 'earth' },
    numerology: { number: 9, meaning: 'Completion, wisdom, attainment' },
    symbols: ['Old man on mountain', 'Lantern with star', 'Long staff', 'Grey robe', 'Snow-covered mountains'],
    love: { upright: 'Need time alone before relationships', reversed: 'Unwelcome isolation' },
    career: { upright: 'Wondering if in right career', reversed: 'Balance isolation with collaboration' },
    health: 'Time for rest and self-care',
    yesNo: 'No',
    advice: 'Withdraw temporarily to seek inner wisdom.'
  },
  {
    number: 10,
    name: { en: 'Wheel of Fortune', zh: '命运之轮', ja: '運命の輪' },
    arcana: 'major',
    keywords: ['destiny', 'fate', 'karma', 'life cycles', 'turning points', 'good luck', 'change', 'fortune'],
    upright: 'The wheel is always turning. Big changes coming. Cherish blissful moments.',
    reversed: 'Resistance to change, bad luck, negative patterns repeating.',
    astrology: { ruling: 'Jupiter', element: 'fire' },
    numerology: { number: 10, meaning: 'Completion of cycle, new beginnings' },
    symbols: ['Giant wheel', 'YHVH letters', 'TARO letters', 'Alchemical symbols', 'Snake', 'Sphinx', 'Four winged creatures'],
    love: { upright: 'Great relationship changes, soulmates', reversed: 'Stagnancy, past mistakes surfacing' },
    career: { upright: 'Major positive career changes', reversed: 'Career setbacks' },
    health: 'Changes in health patterns, break bad cycles',
    yesNo: 'Yes',
    advice: 'Embrace change and trust in life\'s cycles.'
  },
  {
    number: 11,
    name: { en: 'Justice', zh: '正义', ja: '正義' },
    arcana: 'major',
    keywords: ['justice', 'fairness', 'truth', 'law', 'cause and effect', 'karma', 'accountability', 'balance', 'integrity'],
    upright: 'All actions have consequences. Legal matters resolved fairly. Make choices consciously.',
    reversed: 'Injustice, avoidance of karma, being treated unfairly.',
    astrology: { ruling: 'Libra', element: 'air' },
    numerology: { number: 11, meaning: 'Master number, intuition, spiritual insight' },
    symbols: ['Figure between pillars', 'Purple veil', 'Red robe', 'Scales', 'Double-edged sword', 'Crown'],
    love: { upright: 'True honest love, fairness in partnership', reversed: 'Deception, endless arguments' },
    career: { upright: 'Hard work rewarded, past decisions affecting present', reversed: 'Unjust circumstances' },
    health: 'Balance between activity and rest',
    yesNo: 'Yes',
    advice: 'Be honest and act with integrity. Truth will prevail.'
  }
];
